### PR TITLE
Identifying error ID in the output

### PR DESCRIPTION
**Pull request by bricka**

### CODE REVIEW

**Comment by whirm** [comment]
Would you mind fixing the merge conflict? 

Cheers!

**Comment by whirm** [comment]
Also, I'm have not been developing in Kotlin for a few years so I'm not paying much attention to this package. I'd be open to add someone as co-maintainer if anyone is up for it.

**Comment by bricka** [comment]
I've just fixed the merge conflict.

**Comment by bricka** [comment]
And I'll give some thought to maybe being a co-maintainer :)

**Pull request merged**
